#!/usr/bin/env python3
"""Chinese renderings for the SwiftPM command reference pages.

The two lists below are ordered exactly like ``tools/pending_zh.json`` (which
records the English strings that were still missing a translation).  Running
``build_command_page.py`` zips the lists with that inventory, so the entries
must keep their position; adding new English strings means appending the
matching Chinese sentence at the same index.
"""

ITALIC = [
    "包的模板类型：",
    "提供自定义的包名。",
    "显示可以更新的依赖列表。",
    "要更新的包。",
    "要解析到的版本。",
    "要解析到的分支。",
    "要解析到的修订版本。",
    "要解析的包名。",
    "要添加的包的 URL 或目录。",
    "要依赖的精确包版本。",
    "要依赖的特定包修订版本。",
    "要依赖的包的分支。",
    "要依赖的包版本（直到下一个主版本之前）。",
    "要依赖的包版本（直到下一个次版本之前）。",
    "指定包版本区间的上界（不含）。",
    "指定依赖类型。",
    "新产品名称。",
    "要添加的目标类型。",
    "属于该产品的目标列表。",
    "新目标名称。",
    "目标依赖名称列表。",
    "远程二进制目标的 URL。",
    "本地二进制目标的路径。",
    "远程二进制目标的校验和。",
    "生成测试目标时使用的测试库，可以是 'xctest'、'swift-testing' 或 'none' 之一。",
    "新依赖的名称。",
    "要更新的目标名称。",
    "该依赖所在的包。",
    "要添加该设置的目标。",
    "要添加的 Swift 语言设置。支持的设置：experimentalFeature、upcomingFeature、languageMode、strictMemorySafety。",
    "要编辑的修订版本。",
    "要创建的分支。",
    "在该路径创建或使用检出的副本。",
    "要编辑的包的标识。",
    "即使包有未提交、未推送的改动也取消编辑。",
    "要取消编辑的包的标识。",
    "要迁移到指定特性集合的目标。",
    "要迁移到的 Swift 语言即将推出/实验性特性。",
    "列出可用的命令插件。",
    "允许插件写入包目录。",
    "允许插件写入额外的目录。",
    "把可用插件限制为具有给定标识的单个包。",
    "要调用的命令插件的动词。",
    "传给命令插件的实参。",
    "包含应被 API 比较忽略的破坏性变更的文本文件路径。文件中每条被忽略的破坏性变更都应单独占一行，并包含要忽略的确切消息（例如 'API breakage: func foo() has been removed'）。",
    "用作比较基准的 treeish（例如提交哈希、分支名、标签等）。",
    "要纳入 API 比较的一个或多个产品。如果指定，则只比较指定的产品（以及用 `--targets` 指定的目标）。",
    "要纳入 API 比较的一个或多个目标。如果指定，则只比较指定的目标（以及用 `--products` 指定的产品）。",
    "用于存放 API 基准文件的目录路径。如果未指定，将使用临时目录。",
    "重新生成 API 基准，即使已存在可用的基准。",
    "设置输出格式。",
    "输出已解析依赖图的绝对或相对路径。",
    "设置输出格式。可用格式：flatlist（默认）、json",
    "选择要显示特性的包。默认为当前的根包。",
    "把包的工具版本设置为当前正在使用的工具版本。",
    "把包的工具版本设置为给定值。",
    "美化输出 JSON 的格式。",
    "跳过通过类或默认实现继承来的成员。",
    "包含该访问级别及更高访问级别的符号。可能取值：private | fileprivate | internal | package | public | open。",
    "不为通过类或默认实现继承来的成员生成文档注释。",
    "把带 SPI 信息的符号加入符号图。",
    "为外部类型的扩展输出扩展块符号，或者把成员和遵循性直接关联到被扩展的名义类型。",
    "生成的源代码归档的绝对或相对路径。",
    "二进制产物的绝对或相对路径。",
    "要列出的补全类型。",
    "原始的 url 或标识。",
    "镜像的 url 或标识。",
    "获取依赖时不使用共享缓存。",
    "对宏使用预编译的 swift-syntax 库。",
    "不对宏使用预编译的 swift-syntax 库。",
    "在向 TTY 输出时启用彩色诊断信息。默认情况下，连接到 TTY 时启用彩色诊断，否则禁用。",
    "在向 TTY 输出时禁用彩色诊断信息。默认情况下，连接到 TTY 时启用彩色诊断，否则禁用。",
    "不从 netrc 文件加载凭据。",
    "不在 macOS 钥匙串中查找凭据。",
    "不验证从注册表下载的已签名包发布的签名。",
    "打开针对错误行为的运行时检查。",
    "指定要使用的构建系统。",
    "启用传入的包特性。可以通过逗号分隔的列表指定多个特性，例如 `--traits Trait1,Trait2`。在启用特定特性时，还需要通过向该命令传递 `defaults` 来显式启用默认特性。",
    "要为其生成 SBOM 的产品。",
    "用于生成 SBOM 的绝对或相对目录路径。必须与 --sbom-spec 一起使用。（默认：<build_output>/sboms）",
    "要安装的可执行产品名称。",
    "要卸载的可执行文件名称。",
    "要安装的 Swift SDK bundle 的本地文件系统路径或 URL。",
    "用 `swift package compute-checksum` 生成的 bundle 校验和。",
    "要从文件系统移除的 Swift SDK bundle 名称或 Swift SDK ID。",
    "包含 SDK 根目录的目录路径。",
    "包含用于动态链接的 Swift 资源的目录路径。",
    "包含用于静态链接的 Swift 资源的目录路径。",
    "包含头文件的目录路径。可以通过多次向命令提供该选项来指定多个路径。",
    "包含库的目录路径。可以通过多次向命令提供该选项来指定多个路径。",
    "工具集文件的路径。可以通过多次向命令提供该选项来指定多个路径。",
    "重置当前应用到某个 Swift SDK 和目标三元组的配置属性。如果没有指定具体属性，则重置该 Swift SDK 的所有属性。",
    "打印当前应用到某个 Swift SDK 和目标三元组的所有配置属性。",
    "已安装 Swift SDK 的标识符。使用 `list` 子命令查看所有可用的标识符。",
    "要配置的 Swift SDK 的目标三元组。",
    "重置包含 SDK 根目录的目录路径的自定义配置。",
    "重置包含用于动态链接的 Swift 资源的目录路径的自定义配置。",
    "重置包含用于静态链接的 Swift 资源的目录路径的自定义配置。",
    "重置包含头文件的目录路径的自定义配置。",
    "重置包含库的目录路径的自定义配置。",
    "重置工具集文件路径的自定义配置。",
    "由 `sdk-id` 标识字符串指定的 Swift SDK 的目标三元组。",
    "把设置应用于该用户的所有项目。",
    "把注册表与给定作用域关联。",
    "允许使用非 HTTPS 的注册表 URL。",
    "注册表 URL。",
    "注册表的用户名。",
    "注册表的密码。",
    "注册表的访问令牌。",
    "包含访问令牌的文件路径。",
    "允许在无需确认的情况下写入 netrc 文件。",
    "包标识符。",
    "正在创建的包发布版本。",
    "工作文件将写入的目录路径。",
    "包元数据 JSON 文件的路径（当它不是包目录中的 'package-metadata.json' 时）。",
    "要从系统身份存储（如果支持）中获取的签名身份标签。",
    "证书的 PKCS#8 私钥（DER 编码）路径。",
    "签名证书（DER 编码）以及可选的证书链其余部分的路径。证书应按叶子在前、根在后的顺序排列。",
    "仅演练；准备归档并签名，但不发布到注册表。",
    "注册表 URL",
    "要添加的集合的 URL。",
    "所添加集合的排序顺序。",
    "即使集合未签名也信任它。",
    "如果集合已签名则跳过签名检查。",
    "以 JSON 输出",
    "选择搜索方法。",
    "搜索查询。",
    "要获取信息的包或集合的 URL。",
    "要获取信息的包的版本。",
    "要移除的集合的 URL。",
    "为该包启动 Swift REPL。",
    "在调试器会话中启动该可执行文件。",
    "使用提供的实参启动该可执行文件。",
    "跳过构建可执行产品。",
    "要运行的可执行文件。",
    "传给该可执行文件的实参。",
]

PLAIN = [
    "初始化一个新包。",
    "library           - 含有一个库的包。executable        - 含有一个可执行文件的包。tool              - 含有一个使用 Swift Argument Parser 的可执行文件的包。如果你打算提供丰富的命令行参数，请使用这个模板。build-tool-plugin - 提供一个构建工具插件的包。command-plugin    - 提供一个命令插件的包。macro             - 提供一个宏的包。empty             - 只有一个 Package.swift 清单的空包。",
    "更新包依赖。",
    "解析包依赖。",
    "向清单中添加一个包依赖。",
    "向清单中添加一个新产品。",
    "向清单中添加一个新目标。",
    "向清单中添加一个新的目标依赖。",
    "向清单中添加一个新设置。",
    "让包进入可编辑模式。",
    "让包退出可编辑模式。",
    "把包或其各个目标迁移到使用给定的特性集合。",
    "调用命令插件，或者对命令插件执行其他操作。",
    "诊断包中各 Swift 模块的破坏性 API 变更。",
    "diagnose-api-breaking-changes 命令可以把包的 Swift API 与某个基准修订版本进行比较，诊断出其中引入的任何破坏性变更。默认情况下，它会比较基准修订版本中属于某个库产品的每一个 Swift 模块。对于目标很多的包，这种行为可能并不理想，因为比较可能很慢。可以用 `--products` 和 `--targets` 选项来限制比较范围。",
    "描述当前包。",
    "打印已解析的依赖图。",
    "列出该包中可用的可执行文件。",
    "列出某个包可用的特性。",
    "操作当前包的工具版本。",
    "把解析后的 Package.swift 以 JSON 打印出来。",
    "导出符号图。",
    "删除构建产物。",
    "重置整个缓存/构建目录。",
    "清空全局仓库缓存。",
    "为包创建源代码归档。",
    "计算二进制产物的校验和。",
    "用于生成 shell 补全脚本的命令。",
    "为某个依赖设置镜像。",
    "移除已有的镜像。",
    "打印给定包依赖的镜像配置。",
    "生成软件物料清单（SBOM）。",
    "提供安装当前包的可执行产品的能力。",
    "提供卸载此前由 `swift package experimental-install` 安装的可执行产品的能力。",
    "把给定的 Swift SDK bundle 安装到 SwiftPM 能够发现的位置。",
    "如果产物 bundle 位于远程位置，会先把它下载到本地文件系统。",
    "打印文件系统上可用 Swift SDK 的 ID 列表。",
    "从文件系统移除此前安装的 Swift SDK bundle。",
    "管理已安装 Swift SDK 的配置选项。",
    "设置已安装 Swift SDK 的配置选项。",
    "打印当前应用到某个 Swift SDK 和目标三元组的所有配置属性。",
    "重置当前应用到某个 Swift SDK 和目标三元组的配置属性。如果没有指定具体属性，则重置该 Swift SDK 的所有属性。",
    "设置自定义注册表。",
    "用这个子命令在项目级或用户级分配注册表。",
    "在项目级，包管理器会为项目内的包使用该注册表，注册表设置保存在 `.swiftpm/configuration/registries.json` 中。",
    "当你传入 `--global` 选项时，包管理器会在用户级设置注册表：",
    "在用户级，包管理器会为该用户的所有项目使用该注册表，注册表设置保存在 `~/.swiftpm/configuration/registries.json` 中。",
    "上面用户级设置生成的 `registries.json` 示例大致如下：",
    "JSON 键 `[default]` 表示 `https://global.example.com` 上的注册表是「无边界的」，当某个作用域没有找到对应的注册表关联时就会使用它。",
    "要设置特定作用域：",
    "要移除注册表关联，请使用 [`swift package-registry unset` 子命令](../7.5.2-PackageRegistryUnset/)。",
    "移除已配置的注册表。",
    "登录注册表。",
    "包管理器使用注册表服务的登录 API 验证凭据。如果返回成功响应，凭据会被保存到操作系统的凭据存储（例如 macOS 的钥匙串）。在非 macOS 平台上，或者提供了 `--netrc` 标志时，凭据会被保存到用户级 .netrc（默认位于 `~/.netrc`）。位于 ~/.swiftpm/configuration/registries.json 的用户级配置文件也会被更新。",
    "`url` 应当是注册表的基础 URL（例如 `https://example-registry.com`）。如果登录 API 端点的位置不是 `/login`（例如 `https://example-registry.com/api/v1/login`），请提供完整的 URL。",
    "URL 必须是 HTTPS。",
    "下表列出了支持的认证类型及其必需的选项：",
    "| 认证方式                | 必需的选项                |",
    "| ----------------------- | ------------------------- |",
    "| Basic                   |  --username, --password   |",
    "| Token                   |  --token                  |",
    "该工具会分析所提供的选项，以确定认证类型，并在缺少密码/令牌时提示用户（也就是交互模式）。例如，如果只提供了 `--username`，该工具会假定使用基本认证并提示输入密码。",
    "在非交互模式下，请按需提供 `--password` 或 `--token` 选项，或者确保凭据存储中存在该密钥。",
    "如果不支持操作系统的凭据存储，该工具会在把凭据写入安全性较低的 netrc 文件之前提示用户确认。使用 `--no-confirm` 可以禁用这项确认。",
    "要强制使用 netrc 文件而不是操作系统的凭据存储，请传入 `--netrc` 标志。",
    "`example-registry.com` 的条目会被添加到钥匙串。",
    "包管理器更新 `registries.json`，表明 `example-registry.com` 需要基本认证：",
    '{ "authentication": { "example-registry.com": { "type": "basic" }, ... }, ... }',
    "`example-registry.com` 的条目会被添加到 netrc 文件：",
    "包管理器更新 `registries.json`，表明 example-registry.com 需要基本认证：",
    "包管理器更新 `registries.json`，表明 `example-registry.com` 需要基本认证：",
    "如果支持，`example-registry.com` 的条目会被添加到操作系统的凭据存储，否则添加到用户级 netrc 文件：",
    "包管理器更新 `registries.json`，表明 `example-registry.com` 需要令牌认证：",
    "发布到注册表。",
    "这个命令会为包发布创建源代码归档，可选择对它签名，最后把[包发布发布](../../../Design/8.1-RegistryServerSpecification/#4.6.-Create-a-package-release)到注册表。",
    "如果包发布需要认证，包作者应当在运行 `publish` 之前[配置注册表登录](../../../Dependencies/3.2-UsingSwiftPackageRegistry/#Registry-authentication)。",
    "有些证书允许包管理器提取关于签名身份的额外信息。对于用这些证书签名的包，包管理器会执行发布者 TOFU（首次使用即信任），以确保该包的所有版本签名者保持一致。",
    "`--resolver-signing-entity-checking` 选项控制发布者不匹配时应当产生警告（`warn`）还是错误（`strict`）。发布者 TOFU 使用的数据保存在 `~/.swiftpm/security/signing-entities/`。",
    "关于首次使用即信任的更多细节，参见[首次使用即信任](../../../Essentials/1.3-PackageSecurity/#Trust-on-First-Use)。",
    "包作者可以通过设置 `publish` 子命令的 `--metadata-path` 选项来自定义包发布元数据文件的位置。否则，包管理器会在包目录中查找名为 `package-metadata.json` 的文件。",
    "元数据文件的内容必须符合 SE-0391 中定义的 [JSON schema](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0391-package-registry-publish.md#package-release-metadata-standards)。",
    "其他任何要求请参考[注册表规范](../../../Design/8.1-RegistryServerSpecification/#4.2.2.-Package-release-metadata-standards)。",
    "如果注册表要求签名，包作者需要通过设置 `publish` 子命令的 `signing-identity` 选项（用于从操作系统身份存储中读取，例如 macOS 的钥匙串），或者 `private-key-path` 和 `cert-chain-paths` 选项（用于从文件读取）来对包发布签名。这样包管理器就能找到签名密钥和证书。",
    "关于包签名的更多信息，参见[来自注册表的已签名包](../../../Essentials/1.3-PackageSecurity/#Signed-packages-from-a-registry)。",
    "从注册表登出。",
    "如果支持，包管理器会从操作系统的凭据存储中移除凭据，并更新用户级配置文件（`registries.json`）。",
    "为避免意外移除敏感数据，`netrc` 文件需要由用户手动更新。",
    "用户级 `registries.json` 文件中的 `authentication` 键默认位于 `~/.swiftpm/configuration/registries.json`。任何需要认证的包注册表都必须在这个字典中有对应的条目。",
    "`type` 必须是下列之一：",
    "- `basic`：用户名和密码",
    "- `token`：访问令牌",
    "如果支持，把凭据保存在操作系统的原生凭据存储中，否则保存在用户级 netrc 文件中。",
    "关于为每种认证类型配置凭据的更多细节，参见[凭据存储](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0378-package-registry-auth.md#credential-storage)。",
    "添加一个新的集合。",
    "这个子命令添加托管在 Web 上的包集合（要求 HTTPS）：",
    "或者位于本地文件系统中：",
    "可选的 `order` 提示可以用来对集合排序，并可能影响搜索结果中的排序：",
    "包集合的发布者可以[对集合签名以保护其内容](../../../SharingPackages/5.2-PackageCollections/#Protecting-package-collections)。在导入之前，包管理器会检查已签名集合的签名是否有效。如果校验失败，包管理器会返回错误：",
    "用户可以在出现错误的情况下继续添加集合，或者通过传入 `--skip-signature-check` 标志预先跳过对某个包集合的签名检查：",
    "对于托管在 Web 上的包集合，发布者可以要求包管理器[强制实施签名要求](../../../Essentials/1.3-PackageSecurity/#Trusted-root-certificates)。如果某个包集合本应已签名但实际上没有，用户会看到下面这条错误消息：",
    "这种情况下用户不应添加该包集合。",
    "关于签名验证的更多细节，参见[已签名的包集合](../../../Essentials/1.3-PackageSecurity/#Signed-package-collections)。",
    "作为签名验证的一部分，包管理器会[验证证书](../../../Essentials/1.3-PackageSecurity/#Trusted-root-certificates)以确保根证书受信任。",
    "用户在尝试添加未签名的包集合时会得到错误：",
    "要继续，用户必须通过传入 `--trust-unsigned` 标志来确认信任：",
    "`--skip-signature-check` 标志对未签名的集合没有效果。",
    "按关键字或模块名搜索包。",
    "这个子命令在已导入的集合中按关键字或模块名搜索包。结果可以选择用 `--json` 以 JSON 形式返回，便于集成到其他工具中。",
    "使用 `--keywords` 选项时，search 命令会做基于字符串的搜索，并返回与查询匹配的包列表：",
    "使用 `--module` 选项时，search 命令会搜索特定的模块名：",
    "刷新已配置的集合。",
    "这个子命令会手动刷新任何缓存的数据：",
    "SwiftPM 也会在各种情况下自动刷新数据，但搜索之类的某些查询会依赖本地缓存的数据。",
    "列出已配置的集合。",
    "这个子命令列出用户配置的所有集合：",
    "结果可以选择用 `--json` 以 JSON 形式返回，便于集成到其他工具中。",
    "获取某个集合、或者已导入集合中某个包的元数据。",
    "这个子命令显示某个集合、或者已导入集合中某个包的元数据。结果可以选择用 `--json` 以 JSON 形式返回，便于集成到其他工具中。",
    "`describe` 既可用于此前已加入用户配置集合列表的集合，也可用于预览任何其他集合。",
    "如果集合已签名，SwiftPM 会在显示预览之前检查签名是否有效。",
    "用户可以在出现错误的情况下继续预览该集合，或者通过传入 `--skip-signature-check` 标志预先跳过对某个包集合的签名检查：",
    "`describe` 也可以显示已导入集合中某个包的元数据：",
    "用户可以通过传入 `--version` 查看某个包版本的额外元数据：",
    "移除已配置的集合。",
    "这个子命令会从用户已配置的集合列表中移除某个集合：",
    "构建并运行可执行产品。",
    "另见：[swift build](../7.1-SwiftBuild/)、[swift package](../7.3-SwiftPackageCommands/)、[swift test](../7.2-SwiftTest/)",
]

# 命令页中出现的各级标题（命令名保留英文，描述性标题译为中文）
HEADS = {
    "Overview": "概述",
    "Usage": "用法",
    "Project-level": "项目级",
    "User-level": "用户级",
    "Registry settings": "注册表设置",
    "Setting a scope": "设置作用域",
    "Removing a registry": "移除注册表",
    "Changes to registry configuration": "注册表配置的变化",
    "Publisher TOFU": "发布者 TOFU",
    "Package release metadata": "包发布元数据",
    "Package signing": "包签名",
    "Signed package collections": "已签名的包集合",
    "Unsigned package collections": "未签名的包集合",
    "Trusted root certificates": "受信任的根证书",
    "String-based search": "基于字符串的搜索",
    "Module-based search": "基于模块的搜索",
    "Metadata and packages of a collection": "集合的元数据与包",
    "Metadata of a package": "包的元数据",
    "Metadata of a package version": "包版本的元数据",
    "Example: basic authentication (macOS, interactive)": "示例：基本认证（macOS，交互式）",
    "Example: basic authentication (operating system's credential store not supported, interactive)": "示例：基本认证（不支持操作系统的凭据存储，交互式）",
    "Example: basic authentication (use netrc file instead of operating system's credential store, interactive)": "示例：基本认证（改用 netrc 文件而非操作系统的凭据存储，交互式）",
    "Example: basic authentication (operating system's credential store not supported, non-interactive)": "示例：基本认证（不支持操作系统的凭据存储，非交互式）",
    "Example: basic authentication (operating system's credential store not supported, non-interactive, non-default login URL)": "示例：基本认证（不支持操作系统的凭据存储，非交互式，非默认登录 URL）",
    "Example: token authentication": "示例：令牌认证",
}
